// Store the paragraphs inside an array
const paragraphs = [
  "Electronic appliances, gadgets, faster modes of communication, and transport have added to the comfort factor in our lives. It has helped in improving the productivity of individuals and different business enterprises. Technology has brought a revolution in many operational fields. It has undoubtedly made a very important contribution to the progress that mankind has made over the years.",
  "With the advent of technology in communication, which includes telephones, fax machines, cellular phones, the Internet, multimedia, and email, communication has become much faster and easier. It has transformed and influenced relationships in many ways. We no longer need to rely on sending physical letters and waiting for several days for a response.",

  "In the field of travel, cities, towns, states, and countries are using the web to post detailed tourist and event information. Travellers across the globe can easily find information on tourism, sightseeing, places to stay, weather, maps, timings for events, transportation schedules, and buy tickets to various tourist spots and destinations.",

  "Technology has made banking operations very sophisticated and has reduced errors to almost nil, which were somewhat prevalent with manual human activities. Banks are adopting Artificial Intelligence (AI) to increase their efficiency and profits. With the emergence of Internet banking, self-service tools have replaced the traditional methods of banking. ",
  "At present, manufacturing industries are using all the latest technologies, ranging from big data analytics to artificial intelligence. Big data, ARVR (Augmented Reality and Virtual Reality), and IoT (Internet of Things) are the biggest manufacturing industry players. Automation has increased the level of productivity in various fields. It has reduced labour costs, increased efficiency, and reduced the cost of production.",
  "Today, farmers work very differently than they would have decades ago. Data analytics and robotics have built a productive food system. Digital innovations are being used for plant breeding and harvesting equipment. Software and mobile devices are helping farmers harvest better. With various data and information available to farmers, they can make better-informed decisions",
  "Various innovations and development took place in the field of technology which has made a significant impact on our lives in different ways. With the invention of technology, we become more powerful. We have the ability to transform the environment, extend our lifetime, create big and interconnected societies and even explore various new things about the universe.",
  "The future of technology seems to be exciting but also scary. Futuristic predictions in technology can dish out some exciting or scary visions for the future of machines and science. Technology will either enhance or replace the products and activities that are near and dear to us.",
];
